apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/database
patchesStrategicMerge:
- hpa.patch.yaml
- deployment.patch.yaml
- canary.patch.yaml
configMapGenerator:
  - name: database
    files:
      - config.yaml

