apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  -   ../../base/ingress
patchesStrategicMerge:
  - service.patch.yaml
configMapGenerator:
  - name: ingress
    files:
      - envoy.yaml
